version: '3.8'

services:
  pdf_creator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - "log_volume:/logs"
    image: pdf_creator/latest
    restart: unless-stopped
    environment:
      - APP_PORT=${PORT:-8080}
      - APP_LOG_LEVEL=${LOG_LEVEL}
      - APP_LOG_FILE_LEVEL=${LOG_FILE_LEVEL}
volumes:
  log_volume:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /logs